#:kivy 1.8.0

<TomatoLayout>:
    canvas:
        Color:
            rgb: 0, .33, 0
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: 1,1,1,1
        Rectangle:
            size: self.size[1]*0.6, self.size[1]*0.6
            pos: self.center_x - self.size[1]*0.6/2, (self.center_y - self.size[1]*0.6/2)*1.33
            source: 'images/largeicon.png'